apiVersion: v1
kind: Secret
metadata:
  name: quay-io-credentials
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjM0psWlcxMWEyaHBYM05wYm1kaGNtRjVZV05vWlhKMWRuVmZhV0p0SzNGMVlYbGZhVzlmWTNKbFpHVnVkR2xoYkhNNk9WZFJSVk5ITUZoQ05ETkJXRVpUVkZJNFRrOVFVREpLVERoSVNrZEJRMHRETVVNeFNUTTNUVVV5U3pOTFZsb3hSa2szUVVvd1FVNVhVRTR6TWt0Qk1BPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson